version: "3"
services:
  web:
    container_name: docker-jenkins
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./uploads:/home/uploads

